#!/home/namit/iitgn/mujoco_env/bin/python
"""
interactive_finger.py
---------------------
Edit the CONFIG block, run this file — it regenerates finger.xml and
immediately launches the interactive MuJoCo viewer. No separate build step.

Control: Drag the 'tendon_displacement' slider in the viewer's Control panel
(0 to 200 mm). Type a value in the terminal, 's' for slider, 'q' to quit.
"""

import os, sys, time, json, math, threading
import numpy as np
import mujoco
import mujoco.viewer

HERE = os.path.dirname(os.path.abspath(__file__))
XML_PATH = os.path.join(HERE, "finger.xml")

# =====================================================================
#  CONFIG  —  edit these, then just run this file
# =====================================================================

# ---- Geometry (mm) from CAD. Joint axis = +Z for all. ---------------
MCP_CENTER = ( 12.5, 0.0, 0.0)
PIP_CENTER = (-43.0, 0.0, 0.0)
DIP_CENTER = (-84.6, 0.0, 0.0)
TIP_POINT  = (-120.399, 0.0, 0.0)
JOINT_AXIS = (0, 0, 1)

# ---- Palmar (tendon) side -------------------------------------------
PALMAR_NORMAL = (0.0, -1.0, 0.0)

# ---- Routing offsets from each link centerline (mm) -----------------
MCP_OFFSET = 0.0
PIP_OFFSET = 2.0
DIP_OFFSET = 5.0

# ---- Routing fractions along each link (0 = proximal joint end) -----
MCP_ENTRY_FRAC = 0.20;  MCP_EXIT_FRAC   = 0.80
PIP_ENTRY_FRAC = 0.20;  PIP_EXIT_FRAC   = 0.80
DIP_ENTRY_FRAC = 0.20;  DIP_ANCHOR_FRAC = 0.80

# ---- Tendon ---------------------------------------------------------
TENDON_STIFFNESS = 5000.0   # N/m
TENDON_DAMPING   = 1.0
MAX_DELTA_L      = 0.20     # m
TENDON_WIDTH     = 0.0006   # m (visual)

# ---- Joint passive mechanics  ← EDIT STIFFNESS HERE ----------------
MCP_STIFFNESS = 1.0;  PIP_STIFFNESS = 2.0;  DIP_STIFFNESS = 3.0   # N·m/rad
MCP_DAMPING   = 0.08; PIP_DAMPING   = 0.08; DIP_DAMPING   = 0.08  # N·m·s/rad
MCP_RANGE = (-5, 90); PIP_RANGE = (0, 110); DIP_RANGE = (0, 90)   # degrees

# ---- Mass (kg, CAD-reported) ----------------------------------------
M_PROX = 0.01550; M_MID = 0.00679; M_DIST = 0.00391

# ---- Simulation -----------------------------------------------------
TIMESTEP   = 0.002
INTEGRATOR = "implicitfast"
GRAVITY    = (0, 0, -9.81)

# =====================================================================
#  Build finger.xml from CONFIG
# =====================================================================

def _build_xml():
    P = json.load(open(os.path.join(HERE, "params.json")))
    MM = 1e-3
    mcp = np.array(MCP_CENTER); pip = np.array(PIP_CENTER)
    dip = np.array(DIP_CENTER); tip = np.array(TIP_POINT)
    pal = np.array(PALMAR_NORMAL, float); pal /= np.linalg.norm(pal)

    def site(orig, dist, frac, off_mm):
        return ((frac * (dist - orig)) + off_mm * pal) * MM

    sites = {
        "mcp_entry":  ("proximal", site(mcp, pip, MCP_ENTRY_FRAC,  MCP_OFFSET)),
        "mcp_exit":   ("proximal", site(mcp, pip, MCP_EXIT_FRAC,   MCP_OFFSET)),
        "pip_entry":  ("middle",   site(pip, dip, PIP_ENTRY_FRAC,  PIP_OFFSET)),
        "pip_exit":   ("middle",   site(pip, dip, PIP_EXIT_FRAC,   PIP_OFFSET)),
        "dip_entry":  ("distal",   site(dip, tip, DIP_ENTRY_FRAC,  DIP_OFFSET)),
        "dip_anchor": ("distal",   site(dip, tip, DIP_ANCHOR_FRAC, DIP_OFFSET)),
    }
    TENDON_ORIGIN = np.array([0.025, 0.0, 0.0]) + 0.002 * pal

    pos_prox = mcp * MM
    pos_mid  = (pip - mcp) * MM
    pos_dist = (dip - pip) * MM

    def fi(nm):
        I = np.array(P["inertial"][nm]["I"])
        return (f'{I[0,0]:.6e} {I[1,1]:.6e} {I[2,2]:.6e} '
                f'{I[0,1]:.6e} {I[0,2]:.6e} {I[1,2]:.6e}')
    def com(nm):
        c = P["inertial"][nm]["com_body"]
        return f'{c[0]:.6f} {c[1]:.6f} {c[2]:.6f}'
    def mass(nm): return P["inertial"][nm]["m"]
    def v3(a):    return f'{a[0]:.6f} {a[1]:.6f} {a[2]:.6f}'
    def rng(r):
        return f'{r[0]*math.pi/180:.5f} {r[1]*math.pi/180:.5f}'

    site_xml = {}
    for nm, (body, p) in sites.items():
        site_xml.setdefault(body, []).append(
            f'        <site name="{nm}" pos="{v3(p)}" size="0.0015" rgba="0.95 0.5 0.1 1"/>')

    xml = f'''<mujoco model="tendon_finger_3R">
  <!-- Generated by interactive_finger.py — edit CONFIG block above.
       KINEMATICS (mm): MCP={tuple(MCP_CENTER)}  PIP={tuple(PIP_CENTER)}
         DIP={tuple(DIP_CENTER)}  TIP={tuple(TIP_POINT)}
       LINK LENGTHS (mm): proximal={np.linalg.norm(pip-mcp):.2f}  middle={np.linalg.norm(dip-pip):.2f}  distal={np.linalg.norm(tip-dip):.2f}
       TENDON: k={TENDON_STIFFNESS} N/m, c={TENDON_DAMPING}, max deltaL={MAX_DELTA_L} m
       JOINTS: MCP={MCP_STIFFNESS} PIP={PIP_STIFFNESS} DIP={DIP_STIFFNESS} N·m/rad, c=0.08 each -->

  <compiler angle="radian" meshdir="meshes" autolimits="true"/>
  <option timestep="{TIMESTEP}" integrator="{INTEGRATOR}" gravity="{v3(GRAVITY)}"/>

  <default>
    <joint type="hinge" axis="{v3(JOINT_AXIS)}" damping="0.08" stiffness="2.0"/>
    <default class="phalanx">
      <geom type="mesh" rgba="0.78 0.80 0.85 1" contype="1" conaffinity="1"
            condim="3" friction="1 0.05 0.001" density="0"/>
    </default>
    <site group="3"/>
  </default>

  <asset>
    <mesh name="proximal_mesh" file="proximal.stl"/>
    <mesh name="middle_mesh"   file="middle.stl"/>
    <mesh name="distal_mesh"   file="distal.stl"/>
    <texture name="grid" type="2d" builtin="checker" rgb1="0.2 0.25 0.3" rgb2="0.15 0.18 0.22"
             width="300" height="300"/>
    <material name="grid" texture="grid" texrepeat="6 6" reflectance="0.1"/>
  </asset>

  <worldbody>
    <light pos="0 -0.3 0.5" dir="0 0.5 -1" diffuse="0.9 0.9 0.9"/>
    <light pos="0.2 0.2 0.4" dir="-0.3 -0.3 -1" diffuse="0.5 0.5 0.5"/>
    <geom name="floor" type="plane" size="0.5 0.5 0.05" pos="0 0 0" material="grid"/>

    <body name="base" pos="0 0 0.05" euler="0 1.5707963 0">
      <geom name="base_x_axis" type="cylinder" size="0.001" fromto="0 0 0  0.04 0 0" rgba="1 0 0 1" contype="0" conaffinity="0" mass="0"/>
      <geom name="base_y_axis" type="cylinder" size="0.001" fromto="0 0 0  0 0.04 0" rgba="0 1 0 1" contype="0" conaffinity="0" mass="0"/>
      <geom name="base_z_axis" type="cylinder" size="0.001" fromto="0 0 0  0 0 0.04" rgba="0 0 1 1" contype="0" conaffinity="0" mass="0"/>
      <geom type="box" size="0.01875 0.0125 0.0135" pos="0.03125 0 0" rgba="0.3 0.3 0.33 1"
            contype="0" conaffinity="0" density="0" mass="0"/>
      <site name="tendon_origin" pos="{v3(TENDON_ORIGIN)}" size="0.0015" rgba="0.1 0.9 0.3 1"/>

      <body name="proximal" pos="{v3(pos_prox)}">
        <joint name="mcp" stiffness="{MCP_STIFFNESS}" damping="{MCP_DAMPING}" range="{rng(MCP_RANGE)}"/>
        <inertial pos="{com('proximal')}" mass="{mass('proximal'):.6f}" fullinertia="{fi('proximal')}"/>
        <geom class="phalanx" mesh="proximal_mesh"/>
{chr(10).join(site_xml['proximal'])}

        <body name="middle" pos="{v3(pos_mid)}">
          <joint name="pip" stiffness="{PIP_STIFFNESS}" damping="{PIP_DAMPING}" range="{rng(PIP_RANGE)}"/>
          <inertial pos="{com('middle')}" mass="{mass('middle'):.6f}" fullinertia="{fi('middle')}"/>
          <geom class="phalanx" mesh="middle_mesh"/>
{chr(10).join(site_xml['middle'])}

          <body name="distal" pos="{v3(pos_dist)}">
            <joint name="dip" stiffness="{DIP_STIFFNESS}" damping="{DIP_DAMPING}" range="{rng(DIP_RANGE)}"/>
            <inertial pos="{com('distal')}" mass="{mass('distal'):.6f}" fullinertia="{fi('distal')}"/>
            <geom class="phalanx" mesh="distal_mesh"/>
{chr(10).join(site_xml['distal'])}
          </body>
        </body>
      </body>
    </body>
  </worldbody>

  <tendon>
    <spatial name="flexor" width="{TENDON_WIDTH}" rgba="0.9 0.2 0.2 1"
             stiffness="{TENDON_STIFFNESS}" damping="{TENDON_DAMPING}" springlength="-1">
      <site site="tendon_origin"/>
      <site site="mcp_entry"/>
      <site site="mcp_exit"/>
      <site site="pip_entry"/>
      <site site="pip_exit"/>
      <site site="dip_entry"/>
      <site site="dip_anchor"/>
    </spatial>
  </tendon>

  <sensor>
    <jointpos  name="mcp_angle" joint="mcp"/>
    <jointvel  name="mcp_vel"   joint="mcp"/>
    <jointpos  name="pip_angle" joint="pip"/>
    <jointvel  name="pip_vel"   joint="pip"/>
    <jointpos  name="dip_angle" joint="dip"/>
    <jointvel  name="dip_vel"   joint="dip"/>
    <tendonpos name="flexor_length" tendon="flexor"/>
  </sensor>

  <actuator>
    <motor name="tendon_displacement" tendon="flexor"
           ctrlrange="0 {MAX_DELTA_L}" ctrllimited="true" gear="0"/>
  </actuator>
</mujoco>
'''
    with open(XML_PATH, "w") as f:
        f.write(xml)


# =====================================================================
#  Interactive simulation
# =====================================================================

target_disp_mm = None
lock = threading.Lock()
running = True


def input_thread():
    global target_disp_mm, running
    print("\n" + "=" * 60)
    print("  INTERACTIVE TENDON CONTROL")
    print("=" * 60)
    print(f"  Stiffness — MCP: {MCP_STIFFNESS}  PIP: {PIP_STIFFNESS}  DIP: {DIP_STIFFNESS} N·m/rad")
    print("  1. Drag 'tendon_displacement' slider in the viewer")
    print("  2. Type a value (0-200 mm) in the terminal")
    print("  's' → slider control   'q' → quit")
    print("=" * 60)

    while running:
        try:
            val = input("\n  ΔL (mm) > ")
            stripped = val.strip().lower()
            if stripped in ('q', 'quit', 'exit'):
                print("  Input loop ended. Close the viewer window to exit.")
                break
            if stripped in ('s', 'slider'):
                with lock:
                    target_disp_mm = None
                print("  → Switched to slider control")
                continue
            disp = max(0.0, min(200.0, float(stripped)))
            with lock:
                target_disp_mm = disp
            print(f"  → Target set to {disp:.1f} mm")
        except ValueError:
            print("  ✗ Invalid. Enter a number (0-200), 's' for slider, or 'q' to quit.")
        except EOFError:
            break


def main():
    global running

    print("Building finger.xml from CONFIG...")
    _build_xml()
    print(f"  MCP={MCP_STIFFNESS}  PIP={PIP_STIFFNESS}  DIP={DIP_STIFFNESS} N·m/rad  |  "
          f"damping={MCP_DAMPING}")

    model = mujoco.MjModel.from_xml_path(XML_PATH)
    data  = mujoco.MjData(model)

    tendon_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_TENDON, "flexor")
    jids = {n: mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, n)
            for n in ("mcp", "pip", "dip")}

    mujoco.mj_forward(model, data)
    rest_len = data.ten_length[tendon_id]
    print(f"  Flexor rest length: {rest_len * 1000:.2f} mm")
    print(f"  Opening viewer...  (close window to quit)\n")

    threading.Thread(target=input_thread, daemon=True).start()

    current_disp_mm = 0.0
    SMOOTH = 0.05
    last_print = 0.0

    with mujoco.viewer.launch_passive(model, data) as viewer:
        viewer.opt.flags[mujoco.mjtVisFlag.mjVIS_TENDON] = True
        viewer.cam.distance = 0.35
        viewer.cam.elevation = -15
        viewer.cam.azimuth = 140
        viewer.cam.lookat[:] = [0.0, 0.0, 0.06]

        while viewer.is_running():
            step_start = time.time()

            with lock:
                terminal_target = target_disp_mm

            tgt_mm = terminal_target if terminal_target is not None else data.ctrl[0] * 1000.0
            current_disp_mm += (tgt_mm - current_disp_mm) * SMOOTH

            delta_L_m = current_disp_mm / 1000.0
            model.tendon_lengthspring[tendon_id, :] = rest_len - delta_L_m

            mujoco.mj_step(model, data)
            viewer.sync()

            now = time.time()
            if now - last_print > 2.0:
                angles = {n: np.degrees(data.qpos[jid]) for n, jid in jids.items()}
                tension = model.tendon_stiffness[tendon_id] * max(
                    0.0, data.ten_length[tendon_id] - model.tendon_lengthspring[tendon_id, 0])
                sys.stdout.write(
                    f"\r  [ΔL={current_disp_mm:5.1f}mm] "
                    f"MCP={angles['mcp']:6.1f}°  PIP={angles['pip']:6.1f}°  "
                    f"DIP={angles['dip']:6.1f}°  T={tension:6.2f}N   "
                )
                sys.stdout.flush()
                last_print = now

            dt = model.opt.timestep - (time.time() - step_start)
            if dt > 0:
                time.sleep(dt)

    running = False
    print("\n\nViewer closed. Goodbye.")


if __name__ == "__main__":
    main()
